name: anime_app
description: "A new Flutter project."
 
 
publish_to: 'none'  


 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

 
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.6
  go_router: ^14.1.3
  http: ^1.2.1
  fpdart: ^1.1.0
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.0
  shimmer: ^3.0.0
  get: ^4.6.6
  device_preview: ^1.1.0
  connectivity_plus: ^3.0.3
  easy_localization: ^3.0.6
  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^17.2.1+2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  get_it: ^7.7.0
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.2
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

 
flutter:

  uses-material-design: true

  assets:
    - assets/translations/